version: "3"
services:
  kcfconvoy:
    image: kcfconvoy-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: kcfconvoy-dev
    ports:
      - 8887:8888
    environment:
      - PYTHONPATH=/opt/kcfconvoy
    tty: true
    volumes:
      - .:/opt/kcfconvoy/
    command: ["tail", "-f", "/dev/null"]
