version: "4"
services:
  kcfconvoy:
    image: kcfconvoy-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: kcfconvoy-dev
    ports:
      - 8888:8888
    environment:
      TZ: Asia/Tokyo
      - PYTHONPATH=/opt/kcfconvoy
    tty: true
    volumes:
      - .:/opt/kcfconvoy/
      - /etc/localtime:/etc/localtime:ro
    command: ["tail", "-f", "/dev/null"]
